version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zoo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  permitio:
    image: permitio/pdp-v2:latest
    restart: always
    environment:
      - PDP_DEBUG=True
      - PDP_API_KEY=<permit_api_key>"  # Replace <YOUR_API_KEY> with your actual API key
    ports:
      - "7766:7000"

volumes:
  postgres_data:
