version: '3.8'

services:

  fastapi:
    container_name: web_app
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - connection_string=${connection_string}
      - ENV=production
    depends_on:
      - db
      - permitio
    networks:
      - cutenetwork
    restart: on-failure:10

  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: design_app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cutenetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    

  permitio:
    container_name: permit_pdp
    image: permitio/pdp-v2:latest
    restart: always
    environment:
      - PDP_DEBUG=True
      - PDP_API_KEY=${permit_api_key}
    ports:
      - "7766:7000"

volumes:
  postgres_data:

networks:
  cutenetwork:
    driver: bridge
